name: Build

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  # To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable.
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    if: github.repository_owner == 'ocpddev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release

      - name: Upload release artifacts
        run: gh release upload ${{ github.ref_name }} ./target/release/fsf
