name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

env:
  # To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable.
  GH_TOKEN: ${{ github.token }}

jobs:
  build:
    runs-on: ubuntu-latest
    container: redhat/ubi8
    steps:
      - name: Install Prerequisites
        shell: bash
        # copied from https://github.com/rust-lang/rust-analyzer/blob/47a901b9bf1f99b1ec5222d478684fc412d526a5/.github/workflows/release.yaml#L66-L72
        run: |
          dnf install -y 'dnf-command(config-manager)'
          dnf config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo
          dnf install -y git gh llvm-toolset
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --profile minimal -y
          echo "${CARGO_HOME:-$HOME/.cargo}/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --release

      - name: Upload release artifacts
        run: gh release upload ${{ github.ref_name }} ./target/release/fsf
